[package]
name = 'yoorkin/derive_json_schema'
version = '0.1.1'
description = 'Derive JSON schema for MoonBit'

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[[module]]
name = 'derive_json_schema'
source = 'target/wasm/release/build/derive_json_schema.wasm'
abi = 'wasi'

[module.interfaces]
wasi = '0.1.0-unstable'

[[command]]
name = 'derive_json_schema'
module = 'derive_json_schema'
runner = 'wasi'
