[package]
name = 'moonbitlang/json_deriving'
version = '0.1.0'
description = 'Derive JSON schema for MoonBit'

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[[module]]
name = 'json_derive'
source = '../../target/wasm/release/build/internal/cmd/cmd.wasm'
abi = 'wasi'

[module.interfaces]
wasi = '0.1.0-unstable'

[[command]]
name = 'json_derive'
module = 'json_derive'
runner = 'wasi'
